
### 이용 약관 목록
GET {{url}}/terms
Content-Type: application/json

### 이용 약관 동의
POST {{url}}/terms/agreement
Content-Type: application/json

{
  "agreements": [
    {
      "id": 1,
      "agreed": true
    },
    {
      "id": 2,
      "agreed": true
    },
    {
      "id": 3,
      "agreed": false
    }
  ],
  "email": "aa@bb.cc",
  "mobileVerificationToken": "MMa4P1Cupt/BJNlm1Zu0bg=="
}
