
### Signup
POST {{url}}/signup
Content-Type: application/json

{
  "email": "email",
  "password": "password",
  "name": "name",
  "mobileNumber": "mobileNumber"
}

### Exist email
GET {{url}}/exist/email?email=email
Content-Type: application/json