spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kurly
    username: dev
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    ms.study.kurly: debug
    # show jpa sqls and parameter values in log
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    org.hibernate.orm.jdbc.bind: trace